[package]
name = "rustydo"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.27.0", features = ["all-widgets"]}
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }

[[bin]]
name = "rustydo"
path = "src/bin/main.rs"
