# This is a multi-stage Dockerfile. It allows using multiple images in order to
# get a last image with the minimum weight possible

# Primary image, to compile the application
FROM rust:1.79-slim 

# Change the working directory
WORKDIR /app

# Copy the dependency files into the image
COPY Cargo.toml Cargo.toml

# Download the dependencies without compiling the application
RUN cargo fetch

# Copy the source files into the image
COPY ./src ./src

# Compile the application
RUN cargo build --release

# Run the application executable
CMD ["./target/release/rustydo"]
